% Generated by roxygen2: do not edit by hand
% Please edit documentation in R/parallel.plot.R
\name{parallel.plot}
\alias{parallel.plot}
\title{Longitudinal differential dotplot}
\usage{
parallel.plot(
  fcs.SCE,
  assay.i = "normalized",
  cell.clusters,
  condition,
  psig.cutoff = 0.05,
  return.stats = FALSE,
  colors,
  return.mode = "percentage",
  hide.nosig = FALSE,
  log.trans = FALSE,
  size = 3,
  labels.pos,
)
}
\arguments{
\item{fcs.SCE}{A \code{fcs.SCE} object generated through \code{\link[FlowCT:fcs.SCE]{FlowCT::fcs.SCE()}}.}

\item{assay.i}{Name of matrix stored in the \code{fcs.SCE} object from which calculate correlation. Default = \code{"normalized"}.}

\item{cell.clusters}{Name of column containing clusters identified through \code{\link[FlowCT:clustering.flow]{FlowCT::clustering.flow()}}.}

\item{condition}{Column name from the \code{colData(fcs.SCE)} object which contains condition information. De}

\item{psig.cutoff}{P-value cutoff. Default = \code{0.05}.}

\item{return.stats}{Logical indicating if calculated statistics should be returned in a new variable. Default = \code{FALSE}.}

\item{colors}{Vector with colors for plotting.}
  
\item{return.mode}{String for specifying if final resuls should be proportions ("percentage") or raw counts ("counts"). Default = \code{"percentage"}.}

\item{hide.nosig}{Logical indicating whether hiding non-significal cell populations. Default = \code{FALSE}.}

\item{log.trans}{Logarithmic transformation of counts/percentage values?. Default = \code{FALSE}.}

\item{size}{Point size. Default = \code{3}.}

\item{labels.pos}{Position for cell clusters labelling, user should indicate the numeric position (i.e., 1 for first condition, 2 for second, and so on). By default, last condition will be used.}
}
\description{
It draws a differential dot plot (longitudinaly) according condition for each cell cluster identified.
}
\examples{
\dontrun{
parallel.plot(fcs.SCE = fcs, cell.clusters = "SOM_named")
}
}
\keyword{differential}
\keyword{parallel}
\keyword{dotplot}
